### ISSUE TITLE
No results of the extension

### ISSUE THREAD

**Issue by MattiaRedaelli** [SAP-samples/successfactors-extension-calculate-employee-seniority#10]
I opened this issue because I have a problem when I create a new employee: that is the seniority does not show any value (even if I checked that all the points were correct and functioning before). Could anyone tell me why?

![image](https://user-images.githubusercontent.com/102582917/165273610-8ffe62c0-cee8-4f3f-8e16-dbdce718e636.png)

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - Can you check the logs of the srv application and see if an exception is occurring? It should show you that an event was caught and log any exception if the write-back to SuccessFactors failed. Please provide that logfile after generating the workflow.

**Comment by MattiaRedaelli** [comment]
Hi @jmsrpp - i think the problem can be "[enterprise-messaging-amqp] - ERROR occured in asynchronous event processing: TypeError: Cannot read property 'includes' of undefined"
[seniority-calc-srv-2022-04-27 07_22_46.022+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8569795/seniority-calc-srv-2022-04-27.07_22_46.022%2B0000.txt)

**Comment by jmsrpp** [comment]
@MattiaRedaelli - this was our fault, apologies. We made some updates to the sfsf-mobile-appgyver branch that didn't make it into the main branch. I have fixed this. You would need to make the following changes to emp-service.js and rebuild/redeploy to resolve (Lines 12-13):

        let employee = msg.data
        let id = employee.userId

This was due to an update to the event specification where we added the enclosing "data" object to the SFSF event.

**Comment by MattiaRedaelli** [comment]
@jmsrpp - the srv problem has been solved, but the problem is now in the integration center: the operation ends successfully, but I still don't see the results and in the logs I read "Couldn't perform Read Access Logging. Ensure you have also enabled the Read Access Logging switch "(assuming that it tells me to go to" manage audit configuration "and enable" read audit ", but I can't find anything similar). The addim role already has all the permissions related to Audit.

**Comment by jmsrpp** [comment]
@MattiaRedaelli can we have the latest srv logs? It should confirm the write back to SFSF is successful. I get the same thing in integration center. We should be able to see the flow w/o it, but I can also look into this if needed.

**Comment by MattiaRedaelli** [comment]
@jmsrpp - sure, for completeness I also load the sf files

[eventLog_190111.csv](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8584293/eventLog_190111.csv)
[seniority-calc-srv-2022-04-28 15_50_28.743+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8584311/seniority-calc-srv-2022-04-28.15_50_28.743%2B0000.txt)

**Comment by jmsrpp** [comment]
@MattiaRedaelli - it says the UPSERT worked:

2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT   {
2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT     key: 'EmpEmployment/personIdExternal=sdavid,EmpEmployment/userId=sdavid',
2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT     status: 'OK',
2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT     editStatus: 'UPSERTED',
2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT     message: null,
2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT     index: 0,
2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT     httpCode: 200,
2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT     inlineResults: null
2022-04-28T15:45:42.020+0000 [APP/PROC/WEB/0] OUT   }

So we need to double check that the seniority calculation returned a value and that the MDF objects you added in SuccessFactors are syntactically matching what is in the service implementation. Can you please:

Double check lines 71-74 of https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/blob/main/srv/emp-service.js and make sure the field names exist on the entity.

You can also check the OData API Audit Log on the SFSF side to see the payload and request.

**Comment by MattiaRedaelli** [comment]
@jmsrpp - ok, now i upload all the check:

Audit log:
[odata_request_id_body63524.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8585353/odata_request_id_body63524.txt)
[odata_response_id_header63524.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8585354/odata_response_id_header63524.txt)
[odata_request_id_header63524.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8585355/odata_request_id_header63524.txt)
[odata_response_id_body63524.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8585356/odata_response_id_body63524.txt)

Field names:
![image](https://user-images.githubusercontent.com/102582917/165820091-02659872-5f54-49e8-ba2f-ea8e7bf3eae1.png)
![image](https://user-images.githubusercontent.com/102582917/165820168-5369ae84-c498-4d4c-952a-6d6febdb7049.png)

**Comment by jmsrpp** [comment]
@MattiaRedaelli - check your metadata entry in emp-service.js ... it says apipreview12 but your POST says apisalesdemo2

**Comment by MattiaRedaelli** [comment]
ok, now i'll fix it changeing my link in emp-service.js in apisalesdemo2.successfactors.eu:443

edit: the problem hasn't changed, I'm trying to figure out if I can fix it somehow, but the request payload of API audit logs are empty
[odata_response_id_header63849.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8591268/odata_response_id_header63849.txt)
[odata_request_id_header63849.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8591269/odata_request_id_header63849.txt)
[odata_response_id_body63849.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8591272/odata_response_id_body63849.txt)

**Comment by jmsrpp** [comment]
@MattiaRedaelli - no problem but those files are from a GET:

GET https://apisalesdemo2.successfactors.eu/odata/v2/User?%24top=100&%24skip=0&%24orderby=userId&%24select=userId%2Cusername%2Cstatus%2Cemail%2ClastName%2CfirstName%2ClastModifiedDateTime%2CpersonKeyNav&%24expand=personKeyNav%2CpersonKeyNav%2FuserAccountNav&%24filter=status%20in%20%27active%27

The system correctly responded with Francois Trombley's info! I guess this was a result of the AppGyver application or some other query to the User entity.

Make sure the request shows an UPSERT, which is the result of our extension app:

POST https://apisalesdemo2.successfactors.eu/odata/v2/upsert (from your previous message)

If you redeployed the srv after changing the metadata, hopefully it should work now!

**Comment by MattiaRedaelli** [comment]
@Rapp, ***@***.***> - Where can i change this value?

Ottenere Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jmsrpp** [comment]
@MattiaRedaelli you don't need to change anything ... just run another hire or rehire scenario. I was just pointing out that the previous logs didn't indicate a problem, because the API call was associated with a GET from the User entity. Either you need to find the actual logs from the UPSERT, or simply run the process again and check.

**Comment by MattiaRedaelli** [comment]
@jmsrpp - oh sorry i misunderstood. Ok then I'll try again and update you as soon as possible, thanks, but I wanted to ask you one thing: I just need to run the integration to generate the log? because I have already tried several times but it does not generate anything (even by activating "enable all payloads")

update: this is my srv log, maybe can help
[seniority-calc-srv-2022-05-02 07_41_01.159+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8601494/seniority-calc-srv-2022-05-02.07_41_01.159%2B0000.txt)

**Comment by MattiaRedaelli** [comment]
@jmsrpp - I'm sorry to say it, but unfortunately I was unable to unblock myself from the previous situation: the logs are no longer generated and my integrations return logs of this type as a result.
[eventLog_190159.csv](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8603261/eventLog_190159.csv)

**Comment by jmsrpp** [comment]
@MattiaRedaelli - sorry to hear it. You mean there are no new API logs after triggering the latest hire/rehire/term? The csv just shows the correct outbound communication to Event Mesh has occurred. Beyond that, we would need to look at the srv and API audit logs.

**Comment by MattiaRedaelli** [comment]
@jmsrpp - Yes, there are no new API logs after triggering the integration

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - we determined the root cause of the error was this in the srv application:

[enterprise-messaging-amqp] - ERROR occured in asynchronous event processing: Error: Error during request to remote service: No user token (JWT) has been provided. This is strictly necessary for 'OAuth2SAMLBearerAssertion'

This seems to be caused by some corruption of the destination service, as the sfsf-extensibility service did still test successfully, returning a 200. To resolve this, you should redeploy the application and ensure the requisite services are recreated. You can do that by undeploying, as above, but you can remove the --delete-services. Please make sure the destination properties are updated in your mta.yaml as here:

https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/tree/mission/05-DeployCAPApplicationToCloudFoundryAndHANACloud#redeployment

Also noting that we did confirm the extension worked E2E until April 29.

**Comment by MattiaRedaelli** [comment]
Hi James,

so, just to be sure, I run the undeploy, check that the data entered (and check the mta.yaml file) and after that I execute the deploy. Correct?

As soon as I do, I'll update you on the result.

Thanks
Mattia Redaelli
Da: James Rapp ***@***.***>
Inviato: giovedì 5 maggio 2022 17:49
A: SAP-samples/successfactors-extension-calculate-employee-seniority ***@***.***>
Cc: Mattia Redaelli ***@***.***>; Mention ***@***.***>
Oggetto: Re: [SAP-samples/successfactors-extension-calculate-employee-seniority] No results of the extension (Issue #10)

**ATTENZIONE**: Questo messaggio proviene da un ACCOUNT ESTERNO, presta attenzione ad eventuali link o allegati al suo interno.


Hi @MattiaRedaelli<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMattiaRedaelli&data=05%7C01%7Cmattia.redaelli%40derga.it%7Cb0b04610d15f42edde5b08da2eaebf60%7Cbbf156d433fa4fee86f62cfcb1359ef0%7C0%7C0%7C637873625312791099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6f83dbWMbnUm3AmxUmZ3QPOva6h0%2BFyQFV5J9%2FuJ0PE%3D&reserved=0> - we determined the root cause of the error was this in the srv application:

[enterprise-messaging-amqp] - ERROR occured in asynchronous event processing: Error: Error during request to remote service: No user token (JWT) has been provided. This is strictly necessary for 'OAuth2SAMLBearerAssertion'

This seems to be caused by some corruption of the destination service, as the sfsf-extensibility service did still test successfully, returning a 200. To resolve this, you should redeploy the application and ensure the requisite services are recreated. You can do that by undeploying, as above, but you can remove the --delete-services. Please make sure the destination properties are updated in your mta.yaml as here:

https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/tree/mission/05-DeployCAPApplicationToCloudFoundryAndHANACloud#redeployment<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSAP-samples%2Fsuccessfactors-extension-calculate-employee-seniority%2Ftree%2Fmission%2F05-DeployCAPApplicationToCloudFoundryAndHANACloud%23redeployment&data=05%7C01%7Cmattia.redaelli%40derga.it%7Cb0b04610d15f42edde5b08da2eaebf60%7Cbbf156d433fa4fee86f62cfcb1359ef0%7C0%7C0%7C637873625312791099%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=R12Bz692Pmwja%2FcU%2F0uUGH8CqE9wRD6b9tEMTmpUdug%3D&reserved=0>

Also noting that we did confirm the extension worked E2E until April 29.

-

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - following steps:

1. Undeploy
2. Adjust mta.yaml to make sure the destination service is created (e.g. managed-service instead of existing-service)
3. Redeploy
4. Confirm destination service instance is created in subaccount
5. Test hiring / rehiring an employee as before
6. Check srv logs in BTP cockpit to see if the exception is resolved and everything works

**Comment by MattiaRedaelli** [comment]
Hi James,

now the logs are generated correctly, but the error "Couldn't perform read access logging" remains, hope these can help you find a solution.

Thanks
Mattia Redaelli

Da: James Rapp ***@***.***>
Inviato: giovedì 5 maggio 2022 20:59
A: SAP-samples/successfactors-extension-calculate-employee-seniority ***@***.***>
Cc: Mattia Redaelli ***@***.***>; Mention ***@***.***>
Oggetto: Re: [SAP-samples/successfactors-extension-calculate-employee-seniority] No results of the extension (Issue #10)

**ATTENZIONE**: Questo messaggio proviene da un ACCOUNT ESTERNO, presta attenzione ad eventuali link o allegati al suo interno.


Hi @MattiaRedaelli<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMattiaRedaelli&data=05%7C01%7Cmattia.redaelli%40derga.it%7C5401d54dc5024d773ab508da2ec94352%7Cbbf156d433fa4fee86f62cfcb1359ef0%7C0%7C0%7C637873739203571895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xx1Ka9ZCKXW7nJFcdh79cVqRD9VY3AO0yt%2BjG%2F60RIs%3D&reserved=0> - following steps:

  1.  Undeploy
  2.  Adjust mta.yaml to make sure the destination service is created (e.g. managed-service instead of existing-service)
  3.  Redeploy
  4.  Confirm destination service instance is created in subaccount
  5.  Test hiring / rehiring an employee as before
  6.  Check srv logs in BTP cockpit to see if the exception is resolved and everything works

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSAP-samples%2Fsuccessfactors-extension-calculate-employee-seniority%2Fissues%2F10%23issuecomment-1118945430&data=05%7C01%7Cmattia.redaelli%40derga.it%7C5401d54dc5024d773ab508da2ec94352%7Cbbf156d433fa4fee86f62cfcb1359ef0%7C0%7C0%7C637873739203571895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d2jWlOAwn0U315e2qPl2jb9HPmt5v5wJAWZxNwGdk3Q%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAYOUVBLLFMEGJGUTIHTZFKTVIQK5ZANCNFSM5ULISGBA&data=05%7C01%7Cmattia.redaelli%40derga.it%7C5401d54dc5024d773ab508da2ec94352%7Cbbf156d433fa4fee86f62cfcb1359ef0%7C0%7C0%7C637873739203571895%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C1f6lOyqXqLc3RBcNWxdFsldq%2B4v9qL4iM%2Fn8n4rl9k%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

X-Event-ID: EVENT-UNKNOWN-UNKNOWN-or1areboh44s-20220506091403-1089589
CorrelationId: 835cc2a5-349f-49ba-a6c4-f09a6bf34e18
Content-Type: application/json;charset=utf-8
DataServiceVersion: 1.0
Vary: Accept-Encoding
Content-Length: 210
SFODataServerTimeZone: Europe/Amsterdam
Status: 200

POST https://apisalesdemo2.successfactors.eu/odata/v2/upsert

ip address: 52.202.170.155
host: apisalesdemo2.successfactors.eu
x-forwarded-port: 9003
x-forwarded-proto: https
content-length: 248
accept: application/json,text/plain
content-type: application/json
authorization: Bearer **********
user-agent: axios/0.21.4
x-forwarded-host: apisalesdemo2.successfactors.eu
successfactors-origin: API
unique-id: 71f26adc-0596-4667-ab39-c4931a2a961e

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - it looks good. That access logging message isn't important. We again see the upsert coming into SFSF. Can you confirm the employee this is for had their seniority fields updated?

**Comment by MattiaRedaelli** [comment]
Hi @jmsrpp - yes, now it works. Thank you so much.

**Comment by MattiaRedaelli** [comment]
update: I'm sorry to have noticed it only now, but unfortunately the situation has not changed. When I created the test user, I created two, and I notice that while one actually shows results, the other doesn't. Furthermore, the test user which displays the data does not update it over time.

I hope I'm wrong, but if not I need to reopen this thread

![image](https://user-images.githubusercontent.com/102582917/167365586-29e799f6-0529-4ea0-9545-76f0bdcb22c2.png)

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - the screenshot shows a working extension. The seniority values only get updated when an event, such as hire, rehire, or terminate, takes place. Of course, you could extend this to many more events, or update the value automatically for non-events in the MDF, but we aren't doing so in this example extension.

If you think there is a problem, please share the results of the OData Audit Log and the srv logs from the BTP application. Always happy to review with those details. Remember, the read access logging error in the event isn't important.
