### ISSUE TITLE
@ sap-cloud-sdk error

### ISSUE THREAD

**Issue by MattiaRedaelli** [SAP-samples/successfactors-extension-calculate-employee-seniority#13]
hi all, i would need your help to solve an error that keeps appearing every time i run a command like "npm"/ "npx".
I leave you log and images below, does anyone know how to solve it?

![image](https://user-images.githubusercontent.com/102582917/172425018-67bca8eb-e6a0-4a11-be95-505c85e836e8.png)
[2022-06-07T15_42_44_227Z-debug-0.log](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8854691/2022-06-07T15_42_44_227Z-debug-0.log)

I am aware that "npm install -g @ angular / cli @ latest" solves the problem related to "npm install", but the real problem is the command "npx -p @ sap / cds-dk cds build", which I cannot to execute.

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - check the details here please:
https://www.carlrippon.com/upgrading-npm-dependencies/
and you can update to the latest package of sap-cloud-sdk
