### ISSUE TITLE
seniority-calc-db-deployer failed

### ISSUE THREAD

**Issue by horsemanjackyliu** [SAP-samples/successfactors-extension-calculate-employee-seniority#5]
Hi, Gurus,

seniority-calc-db-deployer always failed . 
[seniority-calc-db-deployer-2022-04-02 08_59_59.783+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8402184/seniority-calc-db-deployer-2022-04-02.08_59_59.783%2B0000.txt)

**Comment by horsemanjackyliu** [comment]
Hi, Gurus,

Upgraded the NPM to 8.60,  then the command mbt build will end with error .

**Comment by jmsrpp** [comment]
Hi @I501000 - Thanks for entering this issue in our repository. Can you provide the mbt build output after you ugraded NPM, please? The deployer log seems to be successful, other than complaining about your npm version and some warnings related to plugins in the .hdiconfig file. You could try deleting this file and running 'cds build' command again. It will be recreated when you do so.

Regards,
Jim

**Comment by MattiaRedaelli** [comment]
i have similar issuse
[seniority-calc-db-deployer-2022-04-13 14_34_33.863+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8482306/seniority-calc-db-deployer-2022-04-13.14_34_33.863%2B0000.txt)

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - your logfile specifically errors on the npm verison. Can you run this in the terminal, rebuild the mbt archive, and let me know? please attach the updated logs and we'll take a look.

**Comment by MattiaRedaelli** [comment]
Hi @jmsrpp ,i'm in the same situation as @I501000 , if i upgrade my npm version the command mbt build fail. Now i'll try again (deleting the .hdiconfig file and running cds build).

**Comment by jmsrpp** [comment]
Thanks @MattiaRedaelli - please provide any logs or stdout so I can review.

**Comment by MattiaRedaelli** [comment]
thanks to you @jmsrpp, for convenience I put in a file everything that generated the command, but here is the error

[error_mbt_build.md](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8490798/error_mbt_build.md)

**Comment by jmsrpp** [comment]
@MattiaRedaelli - looks like you have the error here:

https://stackoverflow.com/questions/69567381/getting-cannot-read-property-pickalgorithm-of-null-error-in-react-native

Try clearing the npm cache and repeat the build process, please. Looks like no issue with the cds build.

**Comment by MattiaRedaelli** [comment]
Update: running
npm cache clear --force 
npm set registry=https://registry.npmjs.org/
npm install -g npm@8.7.0

the command now works, but when i try to start seniority-calc-db-deployer in the log there is the same error ("npm notice Run `npm install -g npm@8.7.0` to update!")

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - forgot to mention, please also delete package-lock.json in your project (double check the db/srv too) and rebuild. We need the deployed application to rebuild with the latest dependencies. Feel free to share all the logs here.

**Comment by MattiaRedaelli** [comment]
hi @jmsrpp, unfortunately nothing has changed, the error remains even if the "npm: ^ 8.7.0" field appears in both package.json and package-lock.json.
[seniority-calc-db-deployer-2022-04-14 20_34_20.033+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8492063/seniority-calc-db-deployer-2022-04-14.20_34_20.033%2B0000.txt)

**Comment by jmsrpp** [comment]
@MattiaRedaelli - just to confirm, you deleted all package-lock.json files in your application root, db, and srv folders. You rebuilt the mbt archive and pushed it again to CF?

**Comment by MattiaRedaelli** [comment]
now i'll try again, for be sure, is that correct?

    #type: org.cloudfoundry.managed-service
    type: org.cloudfoundry.existing-service

**Comment by MattiaRedaelli** [comment]
if i re-download the progect, there are these package-lock files?

**Comment by jmsrpp** [comment]
@MattiaRedaelli - if you redownload the project they will be gone. We didn't store them in the repo but probably yours were created with a pre 8.6 version of npm. Thus, deleting and recreating will hopefully work. If so, I can update the README accordingly with this guidance.

**Comment by jmsrpp** [comment]
> now i'll try again, for be sure, is that correct?
> 
> ```
> #type: org.cloudfoundry.managed-service
> type: org.cloudfoundry.existing-service
> ```

Yes that is correct if your event mesh service is already created.

**Comment by MattiaRedaelli** [comment]
to not waste any more time I would say that if it works re-download the project if it works.

thank you so much for all the support

**Comment by MattiaRedaelli** [comment]
Update: I recreated the project from the beginning, installed the new version of "npm", but the error of the "seniority-calc-db-deployer" always remains the same (even if no errors are reported in the terminal and the package is updated to correct time). I also tried to edit the mta.yaml file in the following way:

build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm cache clear --force --production
        - npm set registry=https://registry.npmjs.org/ --production
        - npm install -g npm@8.7.0 --production
        - npx -p @sap/cds-dk cds build --production


[seniority-calc-db-deployer-2022-04-15 14_03_35.481+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8496315/seniority-calc-db-deployer-2022-04-15.14_03_35.481%2B0000.txt)
[SAP_Business.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8496317/SAP_Business.txt)

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - I just deployed the app w/o any problems. I added a step to the README to have you install and update npm dependencies before the initial deployment, but other than that, no issues. In your latest log, seems like everything is working:

Application "seniority-calc-srv" started and available at "<removed>-consulting-cs-srl-btpmission-dev-seniority-calc-srv.cfapps.us10.hana.ondemand.com"

Now, you can add dummy-auth: https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/blob/main/package.json (L 60-62), rebuild, and redeploy. That will allow you to continue the mission. I recently discovered JWT is the default option when you deploy unless you add this property.

**Comment by MattiaRedaelli** [comment]
hi @jmsrpp, I'm sorry not to be able to do the mission correctly, but unfortunately the usual error related to the npm update results, although the deployment goes smoothly, the version is updated and the new changes have been made

[seniority-calc-db-deployer-2022-04-19 11_54_49.012+0000.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8512710/seniority-calc-db-deployer-2022-04-19.11_54_49.012%2B0000.txt)
[Terminal_Output.txt](https://github.com/SAP-samples/successfactors-extension-calculate-employee-seniority/files/8512781/Terminal_Output.txt)

N.B. I was careful to use the new version of the project (I then recreated the fork)

**Comment by jmsrpp** [comment]
Hi @MattiaRedaelli - no worries, your deployment is working fine. I can access the Employee entity at the URL in your application log. I think the error still occurs because of the deployed application in BTP. Most likely, if you delete the deployer/srv from your Cloud Foundry runtime, and redeploy after ensuring you have a fresh package-lock.json the error will go away. However, as your extension is working correctly, I think this is not strictly necessary. Let me know what you would like to do and I can response or close the issue accordingly.

**Comment by jmsrpp** [comment]
Closing as we resolved this by undeploying with --delete-services and redeploying.
