### ISSUE TITLE
Creating Outbound REST Destination

### ISSUE THREAD

**Issue by MattiaRedaelli** [SAP-samples/successfactors-extension-calculate-employee-seniority#6]
save everyone, I have a problem in point 6: how should I connect namespace and topic name within the link?

I am not even clear what the topic name is, in my case it would be "seniority-calc-em"?

Assuming my namespace is "namespace / myspace" and the beginning of the link is https://enterprise-messaging-pubsub.cfapps.us10.hana.ondemand.com, what would my final URL be?

Thank you all

![Immagine 2022-04-08 152030](https://user-images.githubusercontent.com/102582917/162444040-1edbd0d1-638a-431b-b094-2748e900b472.png)

**Comment by nocin** [comment]
Hi, 

I was struggling there too, as the guide is a bit confusing there.
This video helped me understanding the needed syntax: https://youtu.be/UDVb6w5lsqQ

The namespace and topic should look like this:
`/messagingrest/v1/topics/sap%252Fsuccessfactors%252FSFPART057671%252Fisc%252Fcontractchange/messages`

And as another hint: I also had to replace line 12 in emp-service.js from this `let employee = msg.headers` to `let employee = msg.data`, as in "Defining Integration Center Jobs" (step 7) it says "Set the label to data."

Regards
Nico
