### ISSUE TITLE
Hybrid testing in BAS using cds bind

### ISSUE THREAD

**Issue by nocin** [SAP-samples/successfactors-extension-calculate-employee-seniority#7]
Hi,

I successfully worked through the demo and everything is running fine when deployed.

But running the application using `cds watch` in the Bussines Application Studio fails and it returns the hint to bind to the Event Mesh service.
![grafik](https://user-images.githubusercontent.com/35531968/163120961-b0959698-2f3f-4582-af5b-4c20bd97dcc9.png)

So I followed the CAP docs to run the application with "hybrid testing" using `cds bind`.

https://cap.cloud.sap/docs/guides/messaging/event-mesh#run-tests-in-hybrid-setup

But it it seems it is not possible to bind the event mesh service with: `cds bind -2 seniority-calc-em`
![grafik](https://user-images.githubusercontent.com/35531968/163120737-3e706f99-c5d7-4795-86fb-22393111ab5b.png)

I also tried adding the key which is in my case "seniority-calc-em-key": `cds bind -2 seniority-calc-em:seniority-calc-em-key`
But it also fails.

Is it possible to run the application in hybrid mode? If yes, how do I bind the Event Mesh service correctly? 

Thanks & Regards
Nico

**Comment by jmsrpp** [comment]
Hi @nocin - in our case, we simply added the event mesh service key to the VCAP_SERVICES variable, typically in a .env file we exclude from GitHub. I haven't configured the full hybrid setup, but can do so in a couple of days. For now, that error complains that CDS doesn't know the service name from the package.json. Can you confirm the enterprise messaging name is seniority-calc-em in that file?

@hterminasyan - any ideas on this one?

**Comment by nocin** [comment]
Hi @jmsrpp,

thanks for your reply! I did not changed anything in the package.json. It's eqal to the one provided by this repo:
![grafik](https://user-images.githubusercontent.com/35531968/163975060-75bb1585-f5c2-4596-8f43-ed29e211a89e.png)

> Can you confirm the enterprise messaging name is seniority-calc-em in that file?

So I would say no to this, but does the event mesh service name really has to be included in the package.json?
The snippet of the package,json looks similar to the code snippets provided by the CAP docs (see link above). 

I have another project where I use event mesh and there I also use the VCAP_SERVICES in a default-env.json.
I just tested the cds bind command there and it fails too with the same message. So may be it's a more general problem or there is something wrong in both application configs.

But as using default-env.json is obsolet (afaik) and cds bind is the way to go, I think it would be worth finding the correct way to bind the event mesh for a hybrid test.

best regards
Nico

**Comment by hterminasyan** [comment]
hi Nico, 

did you try to add a run configuration, which will generate a .env file and you can connect the services deployed on your CF environment? 

See the screenshot below

<img width="490" alt="image" src="https://user-images.githubusercontent.com/6089525/164301411-c4574944-a36d-46d7-bcfd-59a63a4e651a.png">
<img width="885" alt="image" src="https://user-images.githubusercontent.com/6089525/164302430-229bdb16-a6d7-4661-996d-8e9e9d726a59.png">

**Comment by nocin** [comment]
Hi @hterminasyan,

thanks for your reply! The way you described is creating a .env1 file and pasting in a line starting with VCAP_SERVICES={"hana":[ ... ],"enterprise-messaging":[ ... ] etc.
Running cds watch still results in 
![grafik](https://user-images.githubusercontent.com/35531968/165044875-a3067aca-2523-4fde-82f7-e35849dafe5f.png)
And also the binding in in the run configration is not switching to green, as it could not bind properly. 
![grafik](https://user-images.githubusercontent.com/35531968/165045862-9d4c7aec-7590-430b-8847-b7dbb69c25b9.png)

After copying the exact same lines over to a default-env.json and reformating it to propery json format I could get it up running. 
`{
    "VCAP_SERVICES": {
        "enterprise-messaging": [
            {`
![grafik](https://user-images.githubusercontent.com/35531968/165046985-2c626fde-e2a8-467b-90a4-6717ea0ac8f0.png)

I don't get the difference, why .env1 cannot be parsed, but the default-env.json can.

But neverless, this is not a hybrid run configuration as it is always using the environment varibables. In my understanding the cds bind command should add the event mesh service to the .cdsrv-private.json file, which is only used when running with "--profile hybrid". As it does for hana e.g.:
![grafik](https://user-images.githubusercontent.com/35531968/165046227-cbad2769-e957-4473-adf1-49a4c1cdb779.png)

Of course the event mesh service will never work, if it is not bound when doing local testing.

regards
nico

**Comment by nocin** [comment]
Hi,

I finally found what I was looking for. When trying to bind the event mesh service you have to specifiy the type of service using the "kind" parameter: `cds bind -2 appEventMesh --kind enterprise-messaging`

best regards
Nico
